type User {
  username: String! @unique
  password: String!
  workouts: [Workout] @relation
}

type Workout {
  workoutType: String!
  duration: Float
  exercises: [Exercise!] @relation
  user: User!
}

type Exercise {
  name: String!
  sets: Int
  repsPerSet: Int
  distance: Float
  workout: Workout!
}
