services:
  db:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.1
    ports:
      - "6379:6379"

volumes:
  postgres-data:
